#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /home/marqkend/.MPC/mwc.pl -type make
#
#----------------------------------------------------------------------------


all: Project6

depend: Project6-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.Project6 $(@)

.PHONY: Project6
Project6:
	@$(MAKE) -f Makefile.Project6 all

.PHONY: Project6-depend
Project6-depend:
	@$(MAKE) -f Makefile.Project6 depend

project_name_list:
	@echo Project6
